name: Build & Deploy Spring app

on:
 push:
  branches:
    - main

jobs:
  build-deploy:
   name: Build and Deploy Spring Boot for Beginners
   runs-on: ubuntu-latest
   steps:
   #checking out the code
    - name: Checkout code
      uses: actions/checkout@v4 #helps to checkout the code & it also means that it want to run some actions
    
    #setting up the jdk
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: 17
    
    #running unit tests
    - name: Unit Tests
      run: mvn -B test --file pom.xml
    
    #building the application
    - name: Build the application
      run: |
        mvn clean
        mvn -B package --file pom.xml
